development:
  adapter: mysql2
  encoding: utf8
  database: giv2giv_development
  host: 6f47516f18de9984f5b58d787e7a2906104b11f4.rackspaceclouddb.com
  username: giv2giv
  password: LS(*&#JSp$Lh)DF&S

test:
  adapter: mysql2
  encoding: utf8
  database: giv2giv_test
  host: 6f47516f18de9984f5b58d787e7a2906104b11f4.rackspaceclouddb.com
  username: giv2giv
  password: LS(*&#JSp$Lh)DF&S

production:
  adapter: mysql2
  encoding: utf8
  database: giv2giv_production
  host: 6f47516f18de9984f5b58d787e7a2906104b11f4.rackspaceclouddb.com
  username: giv2giv
  password: LS(*&#JSp$Lh)DF&S
